version: "2.4"

networks:
  software-proyect:
    name: network-msproyect
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
  software-config:
    name: network-config-server
    external: true
services:
  ms-discovery:
    image: ms-discovery:0.0.1
    mem_limit: 150m
    ports:
      - "8762:8762"
    networks:
      - software-proyect
      - software-config
    #environment:
    #  - "EUREKA_URI=http://192.168.0.2:8762/eureka"
    volumes:
      - "/opt/local:/opt/arqutectura/logs"
  ms-gateway:
    image: ms-gateway:0.0.1
    mem_limit: 150m
    ports:
      - "8181:8181"
    networks:
      - software-proyect
      - software-config
    environment:
      - "ZIPKIN_URL=http://192.168.0.2:9411"
      - "EUREKA_URI=http://ms-discovery:8762/eureka"
      - "URI_CONFIG=http://ms-config-server:8889"
    depends_on:
      ms-discovery:
        condition: service_started
    volumes:
      - "/opt/local:/opt/arqutectura/logs"
  ms-customer:
    image: ms-customer:0.0.1
    mem_limit: 200m
    ports:
    - "6945:6945"
    networks:
      - software-proyect
      - software-config
    environment:
      - "ZIPKIN_URL=http://192.168.0.2:9411"
      - "EUREKA_URI=http://ms-discovery:8762/eureka"
      - "URI_CONFIG=http://ms-config-server:8889"
    volumes:
      - "/opt/local:/opt/arqutectura/logs"
    depends_on:
      ms-discovery:
        condition: service_started
  ms-product:
    image: ms-product:0.0.1
    mem_limit: 200m
    ports:
      - "7878:7878"
    networks:
      - software-proyect
      - software-config
    environment:
      - "ZIPKIN_URL=http://192.168.0.2:9411"
      - "EUREKA_URI=http://ms-discovery:8762/eureka"
      - "URI_CONFIG=http://ms-config-server:8889"
    volumes:
      - "/opt/local:/opt/arqutectura/logs"
    depends_on:
      ms-discovery:
        condition: service_started
  ms-sale:
    image: ms-sale:0.0.1
    mem_limit: 200m
    ports:
      - "8743:8743"
    networks:
      - software-proyect
      - software-config
    environment:
      - "ZIPKIN_URL=http://192.168.0.2:9411"
      - "EUREKA_URI=http://ms-discovery:8762/eureka"
      - "URI_CONFIG=http://ms-config-server:8889"
    volumes:
      - "/opt/local:/opt/arqutectura/logs"
    depends_on:
      ms-discovery:
        condition: service_started
    #  ms-config_server:
    #    condition: service_started