spring:
  application:
    name: msCustomer
  h2:
    console:
      enabled: true
server:
  port: ${SERVER_PORT:6545}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}