spring:
  application:
    name: msCustomer
  zipkin:
    base-url: http://localhost:9411
  h2:
    console:
      enabled: true
server:
  port: 6666
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka