### REGISTRAR CLIENTE POR MS-COSTOMER
POST http://localhost:6945/v1/api/customer/save
Content-Type: application/json

{
  "name": "Erwin",
  "lastName": "Alejo",
  "email": "alejo@gamjil.com"
}

### REGISTRAR PASANDO POR GATEWAY
POST http://localhost:8181/ms-customer/v1/api/customer/save
Content-Type: application/json

{
  "name": "Erwin",
  "lastName": "Alejo",
  "email": "alejo@gamjil.com"
}
